#
# bundle exec jekyll serve --config _config.yml,_config_dev.yml
#
###################################
# Site wide configuration
####################################
#
url: "http://127.0.0.1:4000"

#
###################################
# Jekyll configuration
####################################
#

#
###################################
# Site Owner configuration
####################################
#

